### ISSUE TITLE
Memory usage value

### ISSUE THREAD

**Issue by dvapelnik** [warrenguy/munin-docker-containers#1]
`munin-docker-containers` show memory usage at moment when `munin` gets updated isn't it?
As I know all `munin` plugins should show 5 minutes average value of some stat

I'm writing same plugin based on `python` but with daemon which collect data from `docker stats [containerid]` and returns average data about `cpu`, `memory` and `network usage`

My question is actual

**Comment by warrenguy** [comment]
Not sure exactly what you're asking, but: yes, the memory usage statistic is instantaneous at the time munin polls. This is generally the case for non-counter-type metrics. The only time you'll get a 5 minute averaged value is when the metric is a counter, or the system (or whatever you are monitoring) provides a 5 minute average value. I guess you could poll every minute or something and average that value, but I don't really see the point...

**Comment by dvapelnik** [comment]
@warrenguy thanks for reply
I finished with the demon stronghold, which collects statistics and generates averaged value
https://github.com/dvapelnik/docker-spectator
